# Generated by Django 4.2.30 on 2026-07-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, choices=[('Finance Office', 'Finance Office'), ('Registrar Office', 'Registrar Office'), ('Maintenance Office', 'Maintenance Office'), ('Clinic', 'Clinic'), ('Admission/Guidance Office', 'Admission/Guidance Office'), ('HR Office', 'HR Office'), ('BSSW Office', 'BSSW Office'), ('ICES Office', 'ICES Office'), ('BSE Program Head Office', 'BSE Program Head Office'), ('BSPA Program Head Office', 'BSPA Program Head Office'), ('BTVTED/ABELS Program Head Office', 'BTVTED/ABELS Program Head Office'), ('BSA/BSAIS Program Head Office', 'BSA/BSAIS Program Head Office'), ('GAD Program Head Office', 'GAD Program Head Office'), ('Library', 'Library'), ('Admin Office', 'Admin Office'), ('PE Department Office', 'PE Department Office'), ('BSIT Program Head Office', 'BSIT Program Head Office')], max_length=100, null=True),
        ),
    ]
