# Generated by Django 4.2.30 on 2026-07-01 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0005_alter_employee_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cutoff', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_payments', to='dtr_api.employee')),
            ],
            options={
                'ordering': ['year', 'month', 'cutoff'],
                'unique_together': {('employee', 'year', 'month', 'cutoff')},
            },
        ),
    ]
