# Generated by Django 4.2.30 on 2026-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0006_employee_end_date_employee_is_active_fundpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_dirty', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('dirty_since', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sheets Sync State',
            },
        ),
    ]
