# Generated by Django 4.2.30 on 2026-07-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpayment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_payments', to='dtr_api.employee'),
        ),
    ]
