# Generated by Django 4.2.30 on 2026-07-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0010_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='dtr_batch',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='employee',
        ),
    ]
