# Generated by Django 4.2.30 on 2026-07-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0011_alter_attachment_options_remove_attachment_dtr_batch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='dtr_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dtr_api.dtrbatch'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dtr_api.employee'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='fund_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dtr_api.fundpayment'),
        ),
    ]
