# Generated by Django 4.2.30 on 2026-07-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0014_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='supabase_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
