# Generated by Django 4.2.30 on 2026-07-20 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0016_treasurytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of the total budget AFTER this transaction was applied.', max_digits=10),
        ),
    ]
