# Generated by Django 4.2.30 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0017_treasurytransaction_running_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('FUND_EDIT_ADD', 'Fund Edit (Add)'), ('FUND_EDIT_SUB', 'Fund Edit (Subtract)')], max_length=15),
        ),
    ]
