# Generated by Django 4.2.30 on 2026-08-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtr_api', '0019_userprofile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_by_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance anomalies',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='card_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('AM_ARRIVAL', 'AM Arrival'), ('AM_DEPARTURE', 'AM Departure'), ('PM_ARRIVAL', 'PM Arrival'), ('PM_DEPARTURE', 'PM Departure')], max_length=14)),
                ('timestamp', models.DateTimeField()),
                ('scanned_by_name', models.CharField(blank=True, max_length=200)),
                ('scanned_by_role', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('SCAN', 'QR Scan'), ('MANUAL', 'Manual Override')], default='SCAN', max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('proof_image', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='dtr_api.employee')),
                ('linked_anomaly', models.ForeignKey(blank=True, help_text='Set when this record was created as a corrective action from an anomaly', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_records', to='dtr_api.attendanceanomaly')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='attendanceanomaly',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_anomalies', to='dtr_api.employee'),
        ),
        migrations.AddField(
            model_name='attendanceanomaly',
            name='resolved_by_record',
            field=models.ForeignKey(blank=True, help_text='Set when admin creates a corrective AttendanceRecord from this anomaly', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolving_anomalies', to='dtr_api.attendancerecord'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'timestamp'], name='dtr_api_att_employe_e56534_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['timestamp'], name='dtr_api_att_timesta_79cf58_idx'),
        ),
    ]
