# Generated by Django 4.2.30 on 2026-08-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0020_attendanceanomaly_employee_card_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTardinessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cutoff', models.IntegerField()),
                ('late_count', models.IntegerField(default=0)),
                ('minutes_late_total', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tardiness_records', to='dtr_api.employee')),
            ],
            options={
                'unique_together': {('employee', 'year', 'month', 'cutoff')},
            },
        ),
    ]
