# Generated by Django 4.2.30 on 2026-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0021_employeetardinessrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_qr_code',
            field=models.BooleanField(default=False),
        ),
    ]
