# Generated by Django 4.2.30 on 2026-08-22 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtr_api', '0022_employee_has_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Auditor', 'Auditor'), ('PIO', 'PIO'), ('Member', 'Member')], default='Member', max_length=20),
        ),
        migrations.CreateModel(
            name='DTREndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cutoff', models.IntegerField()),
                ('endpoint_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtr_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-cutoff'],
                'unique_together': {('month', 'year', 'cutoff')},
            },
        ),
    ]
