# Generated by Django 4.2.30 on 2026-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtr_api', '0023_dtr_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrendpoint',
            name='holidays_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
